import type { Store } from '../domain/types';

/** Fixed IDs so the active profile can be selected after seeding. */
export const DEMO_ID_THOMAS  = 'demo-thomas-reid';
export const DEMO_ID_ELEANOR = 'demo-eleanor-mitchell';
export const DEMO_ID_YUKI    = 'demo-yuki-tanaka';
export const DEMO_ID_KOFI    = 'demo-kofi-asante';

/**
 * Lightweight prefill descriptors for the onboarding form.
 * One is picked at random when "Try an example profile" is clicked.
 * Fields are locked (read-only) once selected.
 * Images live in public/demo/ — drop the matching .jpg files there.
 */
export const DEMO_PROFILES_PREFILL = [
  {
    id: DEMO_ID_THOMAS,
    name: 'Thomas Reid',
    yearBorn: '1951',
    birthplace: 'Geelong, Victoria',
    bio: 'Retired primary school principal and avid vegetable gardener. Raised four children with wife Barbara and has kept a journal since 1975.',
    gender: 'M' as const,
    personaId: 'journalist' as const,
    photo: '/demo/thomas.jpg' as string | null,
  },
  {
    id: DEMO_ID_ELEANOR,
    name: 'Eleanor Mitchell',
    yearBorn: '1942',
    birthplace: 'Ballarat, Victoria',
    bio: 'Grew up on a farm during the post-war years. Worked at Myer in Melbourne before marrying Gerald and raising three children in Fitzroy.',
    gender: 'F' as const,
    personaId: 'historian' as const,
    photo: '/demo/eleanor.jpg' as string | null,
  },
  {
    id: DEMO_ID_YUKI,
    name: 'Yuki Tanaka',
    yearBorn: '1954',
    birthplace: 'Kyoto, Japan',
    bio: 'Grew up learning ikebana in her mother\'s studio in Kyoto. Moved to Melbourne in 1979 and ran a Japanese cooking school from home for twenty years.',
    gender: 'F' as const,
    personaId: 'grandchild' as const,
    photo: '/demo/yuki.jpg' as string | null,
  },
  {
    id: DEMO_ID_KOFI,
    name: 'Kofi Asante',
    yearBorn: '1976',
    birthplace: 'Kumasi, Ghana',
    bio: 'Raised by a schoolteacher father and market trader mother in Kumasi. Studied engineering in Accra, moved to Manchester in 2001, and coaches youth football on weekends.',
    gender: 'M' as const,
    personaId: 'researcher' as const,
    photo: '/demo/kofi.jpg' as string | null,
  },
];

/**
 * Full four-profile demo store used for both the auto-seed on first visit
 * and the "Try an example profile" onboarding flow.
 * Pass activeId to control which profile is active (defaults to Thomas).
 */
export function getFullDemoStore(activeId: string = DEMO_ID_THOMAS): Store {
  const base = Date.now();
  return {
    activeId,
    profiles: [
      {
        id: DEMO_ID_THOMAS,
        name: 'Thomas Reid',
        yearBorn: '1951',
        birthplace: 'Geelong, Victoria',
        bio: 'Retired primary school principal and avid vegetable gardener. Raised four children with wife Barbara and has kept a journal since 1975.',
        photo: '/demo/thomas.jpg',
        gender: 'M',
        personaId: 'journalist',
        sessions: 1,
        createdAt: base - 86400000 * 15,
        memories: [
          {
            id: 'demo-thomas-mem-1',
            imageUrl: 'https://memorycapturestore.blob.core.windows.net/photos/memory-demo-thomas-mem-1-11gf9.png',
            title: 'A Classroom of Thirty',
            era: '1970s',
            theme: 'Work',
            question: 'What do you remember about your very first day in the classroom?',
            answer: "I had thirty-two kids and I couldn't remember a single name by lunchtime. I was absolutely overwhelmed. I went home that evening and wrote every name on a card with a little note — where they sat, something they'd said. I was up until midnight. By Thursday I had them all. I kept doing the cards for thirty years. Every new class, same thing. Barbara used to say the kitchen table was covered in children's names every February.",
            excerpt: "I had thirty-two kids on my first day and I couldn't remember a single name by lunchtime. I went home and wrote them all on cards.",
            summary: "Thomas recalls his first day as a classroom teacher in 1975 — overwhelmed by thirty-two names and determined to learn every one before the week was out. He went home and made cards, a habit that stayed with him for thirty years.",
            palette: ['var(--bloom-b)', 'var(--bloom-a)', 'var(--bloom-d)'],
            people: [{ text: 'Barbara', relation: 'wife' }],
            places: ['Geelong West Primary School'],
            years: ['1975'],
            createdAt: base - 86400000 * 10,
            transcript: [
              { who: 'ai', text: 'What do you remember about your very first day in the classroom?', ts: 0 },
              { who: 'storyteller', text: "I had thirty-two kids and I couldn't remember a single name by lunchtime. Absolutely overwhelmed. I went home that evening and wrote every name on a card — where they sat, something they'd said. I was up until midnight.", ts: 6 },
              { who: 'ai', text: 'Did the card system actually work?', ts: 32 },
              { who: 'storyteller', text: 'By Thursday I had them all. I kept doing the cards for thirty years. Every new class, same thing. Barbara used to say the kitchen table was covered in children\'s names every February.', ts: 45 },
              { who: 'ai', text: 'That\'s a beautiful ritual. Do you think the children ever knew how hard you worked to learn their names?', ts: 68 },
              { who: 'storyteller', text: "Some of them. Years later I'd run into former students and they'd mention it. One girl — she'd be in her forties now — told me it was the first time a teacher had known her name on the second day. That stayed with me.", ts: 78 },
            ],
          },
          {
            id: 'demo-thomas-mem-2',
            imageUrl: 'https://memorycapturestore.blob.core.windows.net/photos/memory-demo-thomas-mem-2-10tqe.png',
            title: 'The First Tomatoes',
            era: '1980s',
            theme: 'Family',
            question: 'When did the gardening start — was it always something you loved?',
            answer: "Not at all. Barbara and I planted six tomato seedlings along the back fence one spring with no idea what we were doing. By February we had so many tomatoes we were leaving bags on the neighbours' doorsteps. Old Mr Patterson next door was delighted. The young couple on the other side started leaving them back on our porch. We ended up with more tomatoes than we started with. But that was it — we were hooked. The following year we put in beans and zucchini. It just grew from there.",
            excerpt: "Barbara and I planted six seedlings along the back fence. By February we had so many tomatoes we were leaving bags on the neighbours' doorsteps.",
            summary: "The summer Thomas and Barbara planted their first vegetable garden became a running joke in the street — six tomato seedlings turned into an abundance that they couldn't give away fast enough, sparking a gardening passion that filled their weekends for decades.",
            palette: ['var(--bloom-a)', 'var(--bloom-c)', 'var(--bloom-b)'],
            people: [{ text: 'Barbara', relation: 'wife' }],
            places: ['Geelong', 'back garden'],
            years: ['1983'],
            createdAt: base - 86400000 * 5,
            transcript: [
              { who: 'ai', text: 'When did the gardening start — was it always something you loved?', ts: 0 },
              { who: 'storyteller', text: "Not at all. Barbara and I planted six tomato seedlings along the back fence one spring with absolutely no idea what we were doing. Just stuck them in the ground and hoped.", ts: 5 },
              { who: 'ai', text: 'And what happened?', ts: 24 },
              { who: 'storyteller', text: "By February we had so many tomatoes we were leaving bags on the neighbours' doorsteps. Old Mr Patterson next door was delighted. The young couple on the other side started leaving them back on our porch.", ts: 31 },
              { who: 'ai', text: 'So you ended up with more tomatoes than you started with?', ts: 58 },
              { who: 'storyteller', text: "Exactly. But that was it — we were hooked. The following year we put in beans and zucchini. It just grew from there. Thirty years later the back garden is basically a small farm.", ts: 66 },
            ],
          },
        ],
      },
      {
        id: DEMO_ID_ELEANOR,
        name: 'Eleanor Mitchell',
        yearBorn: '1942',
        birthplace: 'Ballarat, Victoria',
        bio: 'Grew up on a farm during the post-war years. Worked at Myer in Melbourne before marrying Gerald and raising three children in Fitzroy.',
        photo: '/demo/eleanor.jpg',
        gender: 'F',
        personaId: 'historian',
        sessions: 1,
        createdAt: base - 86400000 * 30,
        memories: [
          {
            id: 'demo-mem-1',
            imageUrl: 'https://memorycapturestore.blob.core.windows.net/photos/memory-demo-mem-1-134f6.png',
            title: 'The Jam Season',
            era: '1950s',
            theme: 'Family',
            question: 'What do you remember most vividly about summers growing up on the farm?',
            answer: "Jam season. Mum would start in the early morning before the heat set in. She'd have the copper pot going before any of us were awake. The whole kitchen smelled of sugar and stone fruit for days on end — peaches, apricots, plums depending on what had come ripe. We children had to stir and she was very particular about that. No stopping, no lumps. She put up about forty jars every summer and we'd eat the last one sometime around May the following year. I can't smell hot sugar now without being right back in that kitchen.",
            excerpt: 'Mum would start in the early morning, before the heat set in. The whole kitchen smelled of sugar and fruit for days.',
            summary: 'Eleanor recalls the annual summer jam-making ritual on the family farm — her mother rising before dawn, copper pots steaming, the scent of stone fruit filling the house for a week.',
            palette: ['var(--bloom-a)', 'var(--bloom-c)', 'var(--bloom-d)'],
            people: [{ text: 'Mum', relation: 'mother' }],
            places: ['Ballarat farm'],
            years: ['1952'],
            createdAt: base - 86400000 * 20,
            transcript: [
              { who: 'ai', text: 'What do you remember most vividly about summers growing up on the farm?', ts: 0 },
              { who: 'storyteller', text: "Jam season, definitely. Mum would start in the early morning before the heat set in. She'd have the copper pot going before any of us were awake.", ts: 7 },
              { who: 'ai', text: 'What was it like being in that kitchen?', ts: 29 },
              { who: 'storyteller', text: "The whole place smelled of sugar and stone fruit for days — peaches, apricots, plums depending on what had come ripe. We children had to stir and she was very particular. No stopping, no lumps.", ts: 38 },
              { who: 'ai', text: 'How many jars would she make?', ts: 65 },
              { who: 'storyteller', text: "About forty every summer. We'd eat the last one sometime around May the following year. I can't smell hot sugar now without being right back in that kitchen.", ts: 73 },
            ],
          },
          {
            id: 'demo-mem-2',
            imageUrl: 'https://memorycapturestore.blob.core.windows.net/photos/memory-demo-mem-2-12brb.png',
            title: 'First Day at Myer',
            era: '1961',
            theme: 'Work',
            question: 'Tell me about the moment you first walked into work — what was it like?',
            answer: "I wore my best dress and white gloves. Everyone wore gloves then, at least to go anywhere that mattered. The floor manager met me at the door and walked me through to the accessories counter and I thought — this is it, this is my life now. It felt enormous. I was nineteen and I had never been anywhere much except Ballarat and one trip to Sydney with my aunt. Melbourne felt like the whole world. The counter was long and glass and there were scarves and gloves and handbags laid out like a museum.",
            excerpt: 'I wore my best dress and white gloves. The floor manager showed me the glove counter and I thought — this is it, this is my life now.',
            summary: "At nineteen, Eleanor began work at Myer's Bourke Street store in Melbourne. Assigned to the accessories counter in an era when white gloves were still everyday wear, she felt the thrill of her first independent chapter.",
            palette: ['var(--bloom-c)', 'var(--bloom-a)', 'var(--bloom-d)'],
            people: [{ text: 'Floor manager', relation: null }],
            places: ['Myer Bourke Street', 'Melbourne'],
            years: ['1961'],
            createdAt: base - 86400000 * 14,
            transcript: [
              { who: 'ai', text: 'Tell me about the moment you first walked into work — what was it like?', ts: 0 },
              { who: 'storyteller', text: "I wore my best dress and white gloves. Everyone wore gloves then, at least to go anywhere that mattered. The floor manager met me at the door and walked me through.", ts: 8 },
              { who: 'ai', text: 'Where were you placed in the store?', ts: 31 },
              { who: 'storyteller', text: "The accessories counter. Long and glass, with scarves and gloves and handbags laid out like a museum. I thought — this is it, this is my life now.", ts: 40 },
              { who: 'ai', text: 'Had you been to Melbourne much before?', ts: 60 },
              { who: 'storyteller', text: "Barely. One trip to Sydney with my aunt and that was it. I was nineteen. Melbourne felt like the whole world to me then.", ts: 69 },
            ],
          },
          {
            id: 'demo-mem-3',
            imageUrl: 'https://memorycapturestore.blob.core.windows.net/photos/memory-demo-mem-3-13n0u.png',
            title: 'Meeting Gerald',
            era: '1965',
            theme: 'Love',
            question: 'Did you ever meet anyone special through your work at Myer?',
            answer: "Gerald. He came in one Tuesday to buy a birthday present for his mother and he didn't know the first thing about scarves. He kept picking up the wrong weight for the season. I spent about forty minutes with him going through the options and my supervisor was giving me looks the whole time because there were other customers. But Gerald was very earnest about it. He wanted to get it right for her. He came back on Thursday to tell me she had loved it. That was the excuse, anyway. We were engaged by the following Easter.",
            excerpt: "He came in to buy a birthday present for his mother and he didn't know the first thing about scarves. I helped him for about forty minutes.",
            summary: 'Eleanor met her future husband Gerald at the accessories counter — he was buying a scarf for his mother and lingered so long her supervisor noticed. They were married two years later.',
            palette: ['var(--bloom-d)', 'var(--bloom-c)', 'var(--bloom-a)'],
            people: [{ text: 'Gerald', relation: 'husband' }],
            places: ['Myer Bourke Street', 'Melbourne'],
            years: ['1965'],
            createdAt: base - 86400000 * 7,
            transcript: [
              { who: 'ai', text: 'Did you ever meet anyone special through your work at Myer?', ts: 0 },
              { who: 'storyteller', text: "Gerald. He came in one Tuesday to buy a birthday present for his mother and he didn't know the first thing about scarves. He kept picking up the wrong weight for the season.", ts: 6 },
              { who: 'ai', text: 'What happened?', ts: 33 },
              { who: 'storyteller', text: "I spent about forty minutes with him going through options. My supervisor was giving me looks the whole time. But Gerald was very earnest — he wanted to get it exactly right.", ts: 40 },
              { who: 'ai', text: 'Did you see him again?', ts: 67 },
              { who: 'storyteller', text: "He came back on Thursday to say his mother had loved it. That was the excuse, anyway. We were engaged by the following Easter.", ts: 75 },
            ],
          },
        ],
      },
      {
        id: DEMO_ID_YUKI,
        name: 'Yuki Tanaka',
        yearBorn: '1954',
        birthplace: 'Kyoto, Japan',
        bio: "Grew up learning ikebana in her mother's studio in Kyoto. Moved to Melbourne in 1979 and ran a Japanese cooking school from home for twenty years.",
        photo: '/demo/yuki.jpg',
        gender: 'F',
        personaId: 'grandchild',
        sessions: 1,
        createdAt: base - 86400000 * 22,
        memories: [
          {
            id: 'demo-yuki-mem-1',
            imageUrl: 'https://memorycapturestore.blob.core.windows.net/photos/memory-demo-yuki-mem-1-15y7q.png',
            title: "Mother's Ikebana Studio",
            era: '1960s',
            theme: 'Family',
            question: 'What was your mother like when you were growing up?',
            answer: "She had a studio at the back of the house where she taught ikebana. I was not allowed to speak when she was working — I understood this without being told. The sound of scissors, the smell of green stems. She moved the branches until they breathed, that was how I thought of it as a child. She never hurried. Her students would come and go but when it was just her and the flowers, the room was completely still. I think I learned patience there before I learned anything else.",
            excerpt: 'The sound of scissors, the smell of green stems. Okāsan moved the branches until they breathed.',
            summary: "Yuki recalls spending childhood afternoons in her mother's ikebana studio in Kyoto — watching in silence as her mother arranged branches with a patience and precision she has never forgotten.",
            palette: ['var(--bloom-c)', 'var(--bloom-b)', 'var(--bloom-a)'],
            people: [{ text: 'Okāsan', relation: 'mother' }],
            places: ['Kyoto'],
            years: ['1963'],
            createdAt: base - 86400000 * 18,
            transcript: [
              { who: 'ai', text: 'What was your mother like when you were growing up?', ts: 0 },
              { who: 'storyteller', text: "She had a studio at the back of the house where she taught ikebana. I was not allowed to speak when she was working — I understood this without being told.", ts: 7 },
              { who: 'ai', text: 'What do you remember of watching her?', ts: 32 },
              { who: 'storyteller', text: "The sound of scissors, the smell of green stems. She moved the branches until they breathed — that was how I thought of it. She never hurried.", ts: 41 },
              { who: 'ai', text: 'Did you take up ikebana yourself?', ts: 63 },
              { who: 'storyteller', text: "Not seriously. But I think I learned patience there before I learned anything else. That stayed with me.", ts: 72 },
            ],
          },
          {
            id: 'demo-yuki-mem-2',
            imageUrl: 'https://memorycapturestore.blob.core.windows.net/photos/memory-demo-yuki-mem-2-12gez.png',
            title: 'First Melbourne Winter',
            era: '1970s',
            theme: 'Migration',
            question: 'What was the biggest surprise when you first arrived in Melbourne?',
            answer: "The cold. I had never felt cold that got inside the house. In Kyoto, the cold was outside — you came indoors and it was warm. Here in Melbourne it followed you in. The houses were draughty and I did not understand why. Hiroshi had arrived six months before me and he had warned me but I thought he was exaggerating. The first night I slept in three layers and I still woke up cold. I had to learn new words very quickly — heater, draught, doona. Some things you can only learn by needing them.",
            excerpt: 'I had never felt cold that got inside the house. In Kyoto, the cold was outside. Here it followed you in.',
            summary: 'Arriving in Melbourne in 1979, Yuki was startled by her first southern winter — a cold that crept through unfamiliar walls, in a city where she barely knew the words for things she needed most.',
            palette: ['var(--bloom-a)', 'var(--bloom-d)', 'var(--bloom-c)'],
            people: [{ text: 'Hiroshi', relation: 'husband' }],
            places: ['Melbourne', 'Kyoto'],
            years: ['1979'],
            createdAt: base - 86400000 * 11,
            transcript: [
              { who: 'ai', text: 'What was the biggest surprise when you first arrived in Melbourne?', ts: 0 },
              { who: 'storyteller', text: "The cold. I had never felt cold that got inside the house. In Kyoto, the cold was outside — you came indoors and it was warm. Here it followed you in.", ts: 6 },
              { who: 'ai', text: 'Had Hiroshi warned you?', ts: 33 },
              { who: 'storyteller', text: "He had, but I thought he was exaggerating. The first night I slept in three layers and I still woke up cold.", ts: 42 },
              { who: 'ai', text: 'How did you manage?', ts: 61 },
              { who: 'storyteller', text: "I learned new words very quickly — heater, draught, doona. Some things you can only learn by needing them.", ts: 69 },
            ],
          },
        ],
      },
      {
        id: DEMO_ID_KOFI,
        name: 'Kofi Asante',
        yearBorn: '1976',
        birthplace: 'Kumasi, Ghana',
        bio: 'Raised by a schoolteacher father and market trader mother in Kumasi. Studied engineering in Accra, moved to Manchester in 2001, and coaches youth football on weekends.',
        photo: '/demo/kofi.jpg',
        gender: 'M',
        personaId: 'researcher',
        sessions: 1,
        createdAt: base - 86400000 * 12,
        memories: [
          {
            id: 'demo-kofi-mem-1',
            imageUrl: 'https://memorycapturestore.blob.core.windows.net/photos/memory-demo-kofi-mem-1-137uo.png',
            title: 'The Market Before Sunrise',
            era: '1980s',
            theme: 'Family',
            question: 'What is your earliest memory of your mother?',
            answer: "Waking in the dark. Mama would come and shake my shoulder at four in the morning and I would dress quickly because she didn't have time to wait. We would walk to Kumasi Central Market together and I would carry things. The market was a completely different world before the sun came up — cool, quiet, and already busy. Traders setting out cloth, vegetables, fish. Everyone knew their place and their business. By the time the sun was properly up the whole place was loud and full. But that hour before, just us and the other early people — I've never forgotten what that felt like.",
            excerpt: "Mama would wake me at four. The market was a different world before the sun came up — cool, quiet, and already busy.",
            summary: "Kofi recalls being woken before sunrise as a boy to help his mother set up her cloth stall at Kumasi Central Market — a ritual that taught him the language of trade and the value of being first.",
            palette: ['var(--bloom-d)', 'var(--bloom-a)', 'var(--bloom-b)'],
            people: [{ text: 'Mama', relation: 'mother' }],
            places: ['Kumasi Central Market', 'Kumasi'],
            years: ['1984'],
            createdAt: base - 86400000 * 9,
            transcript: [
              { who: 'ai', text: 'What is your earliest memory of your mother?', ts: 0 },
              { who: 'storyteller', text: "Waking in the dark. Mama would shake my shoulder at four in the morning and I would dress quickly because she didn't have time to wait. We walked to Kumasi Central Market and I would carry things.", ts: 5 },
              { who: 'ai', text: 'What was the market like at that hour?', ts: 34 },
              { who: 'storyteller', text: "A completely different world — cool, quiet, and already busy. Traders setting out cloth, vegetables, fish. Everyone knew their place.", ts: 44 },
              { who: 'ai', text: 'How do you remember that time now?', ts: 66 },
              { who: 'storyteller', text: "That hour before the sun was properly up, just us and the other early people — I have never forgotten what that felt like.", ts: 76 },
            ],
          },
          {
            id: 'demo-kofi-mem-2',
            imageUrl: 'https://memorycapturestore.blob.core.windows.net/photos/memory-demo-kofi-mem-2-134s5.png',
            title: "Father's Red Pen",
            era: '1990s',
            theme: 'Education',
            question: 'What did your father teach you about work?',
            answer: "He never said much about it directly. But every night without fail he sat at the kitchen table and marked papers. He was a secondary school teacher and he had a red pen and he would be there until midnight or later. I learned to finish my homework before he came home because I wanted the table to be clear for him. I don't think he knew that was the effect he had. He just worked. Whatever the day had been, whatever had happened, he sat down and he worked. That was the lesson. I didn't understand it as a lesson at the time, but I understood it later.",
            excerpt: 'He marked papers until midnight every night. A red pen and the kitchen table. I learnt to finish my homework before he came home.',
            summary: "Kofi's father graded secondary school papers by kitchen light every night — a quiet image of dedication that shaped how Kofi understood hard work long before he could name it.",
            palette: ['var(--bloom-b)', 'var(--bloom-c)', 'var(--bloom-d)'],
            people: [{ text: 'Father', relation: 'father' }],
            places: ['Kumasi'],
            years: ['1991'],
            createdAt: base - 86400000 * 4,
            transcript: [
              { who: 'ai', text: 'What did your father teach you about work?', ts: 0 },
              { who: 'storyteller', text: "He never said much about it directly. But every night without fail he sat at the kitchen table and marked papers. A red pen. He would be there until midnight or later.", ts: 6 },
              { who: 'ai', text: 'How did that affect you as a child?', ts: 35 },
              { who: 'storyteller', text: "I learned to finish my homework before he came home because I wanted the table clear for him. I don't think he knew that was the effect he had.", ts: 44 },
              { who: 'ai', text: 'When did you realise what that had meant?', ts: 67 },
              { who: 'storyteller', text: "Later. Much later. He just worked — whatever the day had been. I didn't understand it as a lesson at the time, but I understood it eventually.", ts: 76 },
            ],
          },
        ],
      },
    ],
  };
}

/** Legacy single-profile store — kept for any callers that still reference it. */
export function getDemoStore(): Store {
  const full = getFullDemoStore(DEMO_ID_ELEANOR);
  return { activeId: DEMO_ID_ELEANOR, profiles: [full.profiles[1]] };
}
